import mongoose from 'mongoose';

/**
 * Mirrors the Java `com.example.ipc.model.Event` record that flows over the
 * `ipc-events` Kafka topic, plus a little Kafka delivery metadata so the
 * dashboard can show which partition/offset each event landed on.
 */
const eventSchema = new mongoose.Schema(
  {
    // The original event id generated by the producer (UUID). Unique so that
    // re-delivered / idempotent messages don't create duplicate documents.
    eventId: { type: String, required: true, unique: true, index: true },
    type: { type: String, required: true, index: true },
    source: { type: String, required: true },
    payload: { type: String, default: '' },
    // Producer-side timestamp (Instant / ISO-8601 from Kafka).
    timestamp: { type: Date, index: true },
    // Kafka delivery metadata.
    partition: { type: Number },
    offset: { type: String },
    // When this bridge stored the event.
    receivedAt: { type: Date, default: Date.now, index: true },
  },
  { versionKey: false }
);

export const EventModel = mongoose.model('Event', eventSchema);
